[project]
site_name = "Michael Qiu's Blog"
site_author = "Michael Qiu"
site_description = "This is Michael Qiu's personal site."
site_url = "https://gitmichaelqiu.github.io"

repo_url = "https://github.com/gitmichaelqiu/blog"
repo_name = "gitmichaelqiu/blog"
repo = "fontawesome/brands/git-alt"

copyright = "Copyright &copy; 2026 Michael Y. Qiu"

nav = [
    { "Portfolio" = "https://gitmichaelqiu.github.io" },
    { Home = [
        { About = "index.md" },
        { "Some Websites" = "some-websites.md" },
    ] },
    { "My Projects" = [
        { "macOSer Series" = [
            { "DesktopRenamer" = "my-projects/desktoprenamer.md" },
            { "OptClicker" = "my-projects/optclicker.md" },
            { "SpaceSwitcher" = "my-projects/spaceswitcher.md" },
        ] },
        { "LexiGen" = [
            # { "中文版" = [
            #     { LexiGen = "my-projects/lexigen/lexigen-zh.md" },
            #     { "快捷键" = "my-projects/lexigen/keyboard-shortcuts-zh.md" },
            #     { "自定义提示词" = "my-projects/lexigen/customize-prompts-zh.md" }
            # ]},
            { "LexiGen" = "my-projects/lexigen.md" },
            { "Keyboard Shortcuts" = "my-projects/lexigen/keyboard-shortcuts.md" },
            { "Customize Prompts" = "my-projects/lexigen/customize-prompts.md" },
        ] },
        { Utilities = [
            { "Discord Spam Spoiler" = "utilities/discord-spam-spoiler.md" },
        ] },
        { "Other Projects" = "my-projects/other.md" },
    ] },
    { Algorithms = [
        { "Number Theory" = [
            { "GCD & LCM" = "algorithms/number-theory/gcd-lcm.md" },
            { "Euler Sieve" = "algorithms/number-theory/euler-sieve.md" },
        ] },
        { Search = [
            { "A*" = "algorithms/search/a-star.md" },
        ] },
        { "Shortest Path" = [
            { "Bellman Ford" = "algorithms/shortest-path/bellman-ford.md" },
            { "Dijkstra (prioirty_queue)" = "algorithms/shortest-path/dijkstra.md" },
            { Floyd = "algorithms/shortest-path/floyd.md" },
            { SPFA = "algorithms/shortest-path/spfa.md" },
        ] },
        { Sort = [
            { "Sort Overview" = "algorithms/sort/sort-overview.md" },
            { "Bubble Sort" = "algorithms/sort/bubble-sort.md" },
            { "Radix Sort" = "algorithms/sort/radix-sort.md" },
        ] },
        { "Quick Pow" = "algorithms/quick-pow.md" },
        { "Data Structures" = [
            { Bignum = "data-structures/bignum.md" },
            { "Binary Heap" = "data-structures/binary-heap.md" },
            { "Disjoint Set Union" = "data-structures/disjoint-set-union.md" },

            { "Sparse Table" = "data-structures/sparse-table.md" },
            { Stack = "data-structures/stack.md" },
            { Tree = [
                { "Binary Tree Traversals" = "data-structures/tree/binary-tree-traversals.md" },
                { "Segment Tree" = "data-structures/segment-tree.md" },
            ] },
        ] },
        { "OI Tips" = [
            { "Elapsed Time Measurement" = "oi-tips/elapsed-time.md" },
            { "File Read & Write" = "oi-tips/file-read-and-write.md" },
            { "GCC Optimize" = "oi-tips/gcc-optimize.md" },
            { "iostream Acceleration" = "oi-tips/accelerate-ios.md" },
            { "Quick Read & Write" = "oi-tips/qread-and-qwrite.md" },
        ] },
    ] },
    { "Academic Notes" = [
        { "A-Level" = [
            { Physics = [
                { "AS Physics" = "academic-notes/a-level/physics/as-physics.md" },
                { "Copyright Claim" = "academic-notes/a-level/physics/copyright.md" },
            ] },
            { Chemistry = [
                { "Bonding & Structures" = "academic-notes/a-level/chemistry/bonding-and-structures.md" },
                { "Isomerism" = "academic-notes/a-level/chemistry/isomerism.md" },
                { "Organic Compounds" = "academic-notes/a-level/chemistry/organic-compounds.md" },
            ] },
            { "Advanced Math" = [
                { Primes = "academic-notes/a-level/math/primes.md" },
                { Polynomials = "academic-notes/a-level/math/polynomials.md" },
            ] },
        ] },
        { AP = [
            { Calculus = [
                { Limit = "academic-notes/ap/calculus/limit.md" },
                { Differentiation = "academic-notes/ap/calculus/differentiation.md" },
                { "Fundamental Calculus" = "academic-notes/ap/calculus/fundamental-calculus.md" },
            ] },
            { Microeconomics = [
                { "Basic Economic Concept" = "academic-notes/ap/microeconomics/basic-economic-concept.md" },
                { "Demand and Supply" = "academic-notes/ap/microeconomics/demand-and-supply.md" },
                { "Production, Cost and Competition" = "academic-notes/ap/microeconomics/production-cost-and-competition.md" },
            ] },
            { Statistics = [
                { "Unit 1: Exploring One-Variable Data" = [
                    { "1. Summary Statistics" = "academic-notes/ap/statistics/u1/summary-statistics.md" },
                    { "2. Graphical Representations" = "academic-notes/ap/statistics/u1/graphical-representations.md" },
                    { "3. The Normal Distribution" = "academic-notes/ap/statistics/u1/the-normal-distribution.md" },
                ] },
                { "Unit 2: Exploring Two-Variable Data" = [
                    { "1. Tables & Graphs" = "academic-notes/ap/statistics/u2/tables-and-graphs.md" },
                    { "2. Scatterplots & Regression" = "academic-notes/ap/statistics/u2/scatterplots-and-regression.md" },
                    { "3. Experimental Design" = "academic-notes/ap/statistics/u2/experimental-design.md" },
                ] },
                { "Unit 3: Collecting Data" = [
                    { "1. Sampling Methods & Bias" = "academic-notes/ap/statistics/u3/sampling-methods-and-bias.md" },
                    { "2. Experimental Design" = "academic-notes/ap/statistics/u3/experimental-design.md" },
                ] },
                { "Unit 4: Probability, Random Variables, and Probability Distributions" = [
                    { "1. Discrete Random Variables" = "academic-notes/ap/statistics/u4/discrete-random-variables.md" },
                    { "2. Binomial & Geometric Distributions" = "academic-notes/ap/statistics/u4/binomial-geometric-distributions.md" },
                ] },
                { "Unit 5: Sampling Distributions" = [
                    { "1. Sampling Distributions" = "academic-notes/ap/statistics/u5/sampling-distributions.md" },
                ] },
                { "Copyright Claim" = "academic-notes/ap/statistics/copyright.md" },
            ] },
        ] },
        { "体制内" = [
            { "初中地理" = "academic-notes/chinese/geography.md" },
            { "学考生物" = [
                { "细胞的分子组成" = "academic-notes/chinese/cell-composition.md" },
                { "细胞的结构" = "academic-notes/chinese/cell-structure.md" },
            ] },
            { "学考政治" = [
                { "必修一" = "academic-notes/chinese/politics-book-1.md" },
                { "必修二" = "academic-notes/chinese/politics-book-2.md" },
            ] },
            { "学考中国古代史" = "academic-notes/chinese/history-china.md" },
            { "学考化学物质俗名" = "academic-notes/chinese/material-name.md" },
            { "学考抛物运动" = "academic-notes/chinese/projectile-motion.md" },
            { "学考集合" = "academic-notes/chinese/sets.md" },
        ] },
    ] },
    { "Games Reviews" = [
        { "Alan Wake 2" = "games-reviews/alan-wake-2.md" },
        { "Red Dead Redemption 2" = "games-reviews/red-dead-redemption-2.md" },
    ] },
]

extra_javascript = [
    "javascripts/katex.js",
    "https://unpkg.com/katex@0/dist/katex.min.js",
    "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js",
    "https://cdn.jsdelivr.net/npm/svg-pan-zoom@3.5.0/dist/svg-pan-zoom.min.js",
]

extra_css = [
    "https://unpkg.com/katex@0/dist/katex.min.css",
    "stylesheets/desktop-renamer.css",
]

[project.theme]
logo = "images/logo.png"
favicon = "images/favicon.png"
features = [
    "navigation.tabs",
    "navigation.sections",
    "navigation.path",
    "navigation.footer",
    "content.code.copy",
]
custom_dir = "overrides"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/monitor"
toggle.name = "Switch to light mode"
# You can add the colors here if you want them to apply to this mode:
primary = "indigo"
accent = "indigo"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "indigo"
accent = "indigo"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
primary = "indigo"
accent = "indigo"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/gitmichaelqiu"

[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://x.com/mickymike2023"

[[project.extra.social]]
icon = "fontawesome/brands/reddit"
link = "https://www.reddit.com/user/MickyMike2077"

[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]
