[project]
site_name = "Michael Qiu's Blog"
site_author = "Michael Qiu"
site_description = "This is Michael Qiu's personal site."
site_url = "https://mqiu.dev/blog"

repo_url = "https://github.com/gitmichaelqiu/blog"
repo_name = "gitmichaelqiu/blog"
repo = "fontawesome/brands/git-alt"

copyright = "Copyright &copy; 2026 Michael Y. Qiu"

nav = [
    { "Portfolio" = "https://mqiu.dev" },
    { Home = [
        { About = "index.md" },
        # { "Some Websites" = "some-websites.md" },
        { Blog = [
            { "macOS App Recommendation" = [
                { "Browsers" = "blog/apps/browsers.md" },
                { "System Utilities" = "blog/apps/system-utilities.md" },
            ] },
        ] },
    ] },
    { "My Projects" = [
        { Overview = "my-projects/overview.md" },
        { "macOSer Series" = [
            { "DesktopRenamer" = "my-projects/desktoprenamer.md" },
            { "OptClicker" = "my-projects/optclicker.md" },
            { "SpaceSwitcher" = "my-projects/spaceswitcher.md" },
        ] },
        { "LexiGen" = [
            { "LexiGen" = "my-projects/lexigen.md" },
            { "Keyboard Shortcuts" = "my-projects/lexigen/keyboard-shortcuts.md" },
            { "Customize Prompts" = "my-projects/lexigen/customize-prompts.md" },
        ] },
        { "Other Projects" = [
            { "Discord Spam Spoiler" = "my-projects/other-projects/discord-spam-spoiler.md" },
            { "Other Projects" = "my-projects/other-projects/other.md" },
        ] },
    ] },
    { Algorithms = [
        { "Number Theory" = [
            { "GCD & LCM" = "algorithms/number-theory/gcd-lcm.md" },
            { "Euler Sieve" = "algorithms/number-theory/euler-sieve.md" },
        ] },
        { Search = [
            { "A*" = "algorithms/search/a-star.md" },
        ] },
        { "Shortest Path" = [
            { "Bellman Ford" = "algorithms/shortest-path/bellman-ford.md" },
            { "Dijkstra" = "algorithms/shortest-path/dijkstra.md" },
            { Floyd = "algorithms/shortest-path/floyd.md" },
            { SPFA = "algorithms/shortest-path/spfa.md" },
        ] },
        { Sort = [
            { "Sort Overview" = "algorithms/sort/sort-overview.md" },
            { "Bubble Sort" = "algorithms/sort/bubble-sort.md" },
            { "Radix Sort" = "algorithms/sort/radix-sort.md" },
        ] },
        { "Quick Pow" = "algorithms/quick-pow.md" },
        { "Data Structures" = [
            { Bignum = "data-structures/bignum.md" },
            { "Binary Heap" = "data-structures/binary-heap.md" },
            { "Disjoint Set Union" = "data-structures/disjoint-set-union.md" },
            { "Sparse Table" = "data-structures/sparse-table.md" },
            { Stack = "data-structures/stack.md" },
            { Tree = [
                { "Binary Tree Traversals" = "data-structures/tree/binary-tree-traversals.md" },
                { "Segment Tree" = "data-structures/segment-tree.md" },
            ] },
        ] },
        { "OI Tips" = [
            { "Elapsed Time Measurement" = "oi-tips/elapsed-time.md" },
            { "File Read & Write" = "oi-tips/file-read-and-write.md" },
            { "GCC Optimize" = "oi-tips/gcc-optimize.md" },
            { "iostream Acceleration" = "oi-tips/accelerate-ios.md" },
            { "Quick Read & Write" = "oi-tips/qread-and-qwrite.md" },
        ] },
    ] },
    { "Data Science" = [
        { "Introduction" = [
            { "Set up Environment" = "data-science/set-up-environment.md" },
        ] },
        { "Pipelines" = [
            { "MLTabularPipelines" = "data-science/mltabpipe.md" },
        ] },
        { "Competition Writeups" = [
            { "Predict Customer Churn" = "data-science/competitions/predict-customer-churn.md" },
        ] },
    ] },
    { "Academic Notes" = [
        { "A-Level" = [
            { Physics = [
                { "AS Physics Problem Collection" = "academic-notes/a-level/physics/physics-problem-collection.md" },
                { "AS Physics Summary" = "academic-notes/a-level/physics/as-physics.md" },
                { "Copyright Claim" = "academic-notes/a-level/physics/copyright.md" },
            ] },
            { Chemistry = [
                { "AS Chemistry Problem Collection" = "academic-notes/a-level/chemistry/chemistry-problem-collection.md" },
                { "Bonding & Structures" = "academic-notes/a-level/chemistry/bonding-and-structures.md" },
                { "Isomerism" = "academic-notes/a-level/chemistry/isomerism.md" },
                { "Organic Compounds" = "academic-notes/a-level/chemistry/organic-compounds.md" },
                { "Periods & Groups" = "academic-notes/a-level/chemistry/periods-and-groups.md" },
            ] },
            { "Advanced Math" = [
                { Primes = "academic-notes/a-level/math/primes.md" },
                { Polynomials = "academic-notes/a-level/math/polynomials.md" },
            ] },
        ] },
        { AP = [
            { Calculus = [
                { Limit = "academic-notes/ap/calculus/limit.md" },
                { Differentiation = "academic-notes/ap/calculus/differentiation.md" },
                { "Fundamental Calculus" = "academic-notes/ap/calculus/fundamental-calculus.md" },
            ] },
            { Economics = [
                { "Quick Guide from AS to AP Macroeconomics" = "academic-notes/ap/macroeconomics/quick-guide-from-as-to-ap-macro.md" },
                { "Basic Economic Concept" = "academic-notes/ap/macroeconomics/basic-economic-concept.md" },
                { "Demand and Supply" = "academic-notes/ap/macroeconomics/demand-and-supply.md" },
                { "Production, Cost and Competition" = "academic-notes/ap/macroeconomics/production-cost-and-competition.md" },
                { "Economics Indicators" = "academic-notes/ap/macroeconomics/economics-indicators.md" },
            ] },
            { "Physics C: Mechanics" = [
                { "Quick Guide from AS to AP Mechanics" = "academic-notes/ap/mechanics/quick-guide-from-as-to-ap-mechanics.md"},
                { "AP Mechanics Problem Collection" = "academic-notes/ap/mechanics/mechanics-problem-collection.md"},
            ] },
            { Statistics = [
                { "Summaries" = [
                    { "AP Statistics Problem Collection" = "academic-notes/ap/statistics/summaries/statistics-problem-collection.md" },
                    { "Hypothesis Test & Confidence Interval" = "academic-notes/ap/statistics/summaries/hypothesis-test-and-confidence-interval.md" },
                    { "Determine Tests" = "academic-notes/ap/statistics/summaries/determine-tests.md" },
                ] },
                { "Unit 1: Exploring One-Variable Data" = [
                    { "1. Summary Statistics" = "academic-notes/ap/statistics/u1/summary-statistics.md" },
                    { "2. Graphical Representations" = "academic-notes/ap/statistics/u1/graphical-representations.md" },
                    { "3. The Normal Distribution" = "academic-notes/ap/statistics/u1/the-normal-distribution.md" },
                ] },
                { "Unit 2: Exploring Two-Variable Data" = [
                    { "1. Tables & Graphs" = "academic-notes/ap/statistics/u2/tables-graphs.md" },
                    { "2. Scatterplots & Regression" = "academic-notes/ap/statistics/u2/scatterplots-regression.md" },
                    { "3. Experimental Design" = "academic-notes/ap/statistics/u2/experimental-design.md" },
                ] },
                { "Unit 3: Collecting Data" = [
                    { "1. Sampling Methods & Bias" = "academic-notes/ap/statistics/u3/sampling-methods-bias.md" },
                    { "2. Experimental Design" = "academic-notes/ap/statistics/u3/experimental-design.md" },
                ] },
                { "Unit 4: Probability, Random Variables, and Probability Distributions" = [
                    { "1. Discrete Random Variables" = "academic-notes/ap/statistics/u4/discrete-random-variables.md" },
                    { "2. Binomial & Geometric Distributions" = "academic-notes/ap/statistics/u4/binomial-and-geometric-distributions.md" },
                ] },
                { "Unit 5: Sampling Distributions" = [
                    { "1. Sampling Distributions" = "academic-notes/ap/statistics/u5/sampling-distributions.md" },
                ] },
                { "Unit 6: Inference for Categorical Data: Proportions" = [
                    { "1. Introduction to Inferences" = "academic-notes/ap/statistics/u6/introduction-to-inferences.md" },
                    { "2. Inference for Proportions" = "academic-notes/ap/statistics/u6/inference-for-proportions.md" },
                    { "3. Errors in Hypothesis Tests" = "academic-notes/ap/statistics/u6/errors-in-hypothesis-tests.md" },
                ] },
                { "Unit 7: Inference for Quantitative Data: Means" = [
                    { "1. Inference for Means" = "academic-notes/ap/statistics/u7/inference-for-means.md" },
                ] },
                { "Unit 8: Inference for Categorical Data: Chi-Square" = [
                    { "1. Goodness of Fit" = "academic-notes/ap/statistics/u8/goodness-of-fit.md" },
                    { "2. Independence and Homogeneity" = "academic-notes/ap/statistics/u8/independence-and-homogeneity.md" },
                ] },
                { "Unit 9: Inference for Quantitative Data: Slopes" = [
                    { "1. Inference for Regression Slopes" = "academic-notes/ap/statistics/u9/inference-for-regression-slopes.md" },
                ] },
                { "Copyright Claim" = "academic-notes/ap/statistics/copyright.md" },
            ] },
        ] },
        { "体制内" = [
            { "初中地理" = "academic-notes/chinese/geography.md" },
            { "学考生物" = [
                { "细胞的分子组成" = "academic-notes/chinese/cell-composition.md" },
                { "细胞的结构" = "academic-notes/chinese/cell-structure.md" },
            ] },
            { "学考政治" = [
                { "必修一" = "academic-notes/chinese/politics-book-1.md" },
                { "必修二" = "academic-notes/chinese/politics-book-2.md" },
            ] },
            { "学考中国古代史" = "academic-notes/chinese/history-china.md" },
            { "学考化学物质俗名" = "academic-notes/chinese/material-name.md" },
            { "学考抛物运动" = "academic-notes/chinese/projectile-motion.md" },
            { "学考集合" = "academic-notes/chinese/sets.md" },
        ] },
    ] },
    { "Games Reviews" = [
        { "Alan Wake 2" = "games-reviews/alan-wake-2.md" },
        { "Red Dead Redemption 2" = "games-reviews/red-dead-redemption-2.md" },
    ] },
]

extra_javascript = [
    "https://unpkg.com/svg-pan-zoom@3.6.1/dist/svg-pan-zoom.min.js",
    "javascripts/pan_loader.js",
]

extra_css = [
    "https://unpkg.com/katex@0/dist/katex.min.css",
    "stylesheets/desktop-renamer.css",
    "stylesheets/sheet.css",
    "stylesheets/pan_zoom.css",
    "stylesheets/theme-override.css?v2",
]

[project.theme]
logo = "images/logo-mq.svg"
favicon = "images/favicon.png"
features = [
    "navigation.tabs",
    "navigation.sections",
    "navigation.path",
    "navigation.footer",
    "content.code.copy",
    "navigation.top",
]
custom_dir = "overrides"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"
primary = "indigo"
accent = "indigo"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "indigo"
accent = "indigo"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
primary = "indigo"
accent = "indigo"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/gitmichaelqiu"

[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://x.com/mickymike2023"

[[project.extra.social]]
icon = "fontawesome/brands/reddit"
link = "https://www.reddit.com/user/MickyMike2077"

[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
toc = { permalink = true }
"pymdownx.arithmatex" = { generic = true, smart_dollar = true }
"pymdownx.betterem" = { smart_enable = "all" }
"pymdownx.caret" = {}
"pymdownx.details" = {}
"pymdownx.emoji" = { emoji_generator = "zensical.extensions.emoji.to_svg", emoji_index = "zensical.extensions.emoji.twemoji" }
"pymdownx.highlight" = {}
"pymdownx.inlinehilite" = { custom_inline = [
    { name = "math", class = "arithmatex", format = "zensical_plugins.render_utils.render_katex" }
] }
"pymdownx.keys" = {}
"pymdownx.mark" = {}
"pymdownx.smartsymbols" = {}
"pymdownx.superfences" = { custom_fences = [
    { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
    { name = "sheet", class = "sheet", format = "zensical_plugins.render_utils.render_sheet" },
    { name = "math", class = "arithmatex", format = "zensical_plugins.render_utils.render_katex" },
] }
"pymdownx.tabbed" = { alternate_style = true }
"pymdownx.tasklist" = { custom_checkbox = true }
"pymdownx.tilde" = {}
"pymdownx.snippets" = {}
